### ISSUE TITLE
Hi, how do you feed data to the charts from django?

### ISSUE THREAD

**Issue by chicodelacruz** [app-generator/django-gradient-able#10]

**Comment by P3RI9** [comment]
I did it using passing a json options object to the html template on the context on a django view., filling the fields of the options that you want to use with python viariables, such as `series` or `categories` . This variables have to be with [apexcharts sintax]( https://apexcharts.com/docs/series/)
`
import json
options = {
        'chart': {
            'height': 350,
            'type': 'bar',
            'stacked': True,
            'zoom': {
                'enabled': True
            }
        },
        'plotOptions': {
            'bar': {
                'horizontal': False,
                'columnWidth': '55%'
            },
        },
        'dataLabels': {
            'enabled': False
        },
        'colors': colors,
        'stroke': {
            'show': True,
            'width': 2,
            'colors': ['transparent']
        },
        'fill': {
            'type': 'gradient',
            'gradient': {
                'shade': 'light',
                'type': "vertical",
                'shadeIntensity': 0.25,
                'inverseColors': True,
                'opacityFrom': 1,
                'opacityTo': 0.7,
                'stops': [50, 100]
            },
        },
        'series': series,
        'xaxis': {
            'categories': categories
        },
        'yaxis': {
            'title': {
                'text': y_axis_title
            }
        }
    }
context['options'] = json.dumps(options)
`

Then, in javascript section of the template get the js object using django json template tag with: 
`{{ options|json_script:"options_json" }}
var options =  JSON.parse(JSON.parse(document.getElementById('options_json').textContent));`
And create the cart 
`var chart = new ApexCharts(
							document.querySelector("#bar-chart-{{ chart_name|slugify }}"),
							options
						);`

**Comment by app-generator** [comment]
Hello guys!

Here is a chart sample provided in Django for multiple chart libraries: 
https://github.com/app-generator/sample-django-charts-multiple

P.S. Thank you for using this starter
